on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    runs-on: ubuntu-18.04
    name: Evaluator job
    steps:
      - name: Wait for build to succeed
        uses: betrybe/action-wait-for-check@v2
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: codeclimate
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: actions/checkout@v2
        if: steps.wait-for-build.outputs.conclusion == 'success'
      - name: Cypress evaluator step
        id: cypress
        uses: betrybe/cypress-evaluator-action@v4
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          repository-test-name: 'betrybe/sd-0x-block6-project-facebook-signup-tests'
          repository-test-branch: 'master'
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        if: steps.wait-for-build.outputs.conclusion == 'success'
        with:
          evaluation-data: ${{ steps.cypress.outputs.result }}
          environment: production
          pr-number: ${{ github.event.number }}