on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    runs-on: ubuntu-18.04
    name: Evaluator job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.3
        with:
          node-version: '12'
      - name: Static code analysis step
        uses: betrybe/eslint-linter-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Evaluator step
        id: evaluator
        uses: betrybe/stryker-evaluator-action@v1.1
        with:
          repository-test-name: 'betrybe/sd-0x-block16-react-tests-tests'
          repository-test-branch: 'master'
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ steps.evaluator.outputs.pr-number }}
